config/routes.rb
Rails.application.routes.draw do
  resources :teams
  devise_for :users
  resources :tasks
  get 'home/index'

  resources :projects
  resources :clients

  root 'home#index'
  

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, presence: true

  has_many :project

  def to_s
    name
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
<% if @client.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@client.errors.count, "error") %>
    prohibited this client from being saved:</h2>

  <ul>
    <% @client.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <div class="col-md-6">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="clearfix"></div>
<br>
<div class="col-md-12">
  <div class="actions pull-right">
    <%= f.submit "Salvar Cliente", class: "btn btn-warning" %>
  </div>
</div>
<% end %>

app/views/clients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <h5 class="col-md-10">Editando Cliente</h5>
          </div>
        </div>
        <div class="panel-body">
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container">
  <div class="row">

    <p id="notice"><%= notice %></p>

    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <h5 class="col-md-10">Listagem de Clientes</h5>
            <div class="col-md-2">
              <%= link_to new_client_path, class: "btn btn-warning pull-right" do %><b>Novo Cliente</b><% end %>
            </div>
          </div>
        </div>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th class="col-md-2"></th>
            </tr>
          </thead>
          <tbody>
            <% @clients.each do |client| %>
            <tr>
              <td><%= client.id %></td>
              <td><%= client.name %></td>
              <td>
                <div class="btn-group pull-right">
                  <%= link_to client, class: "btn btn-info" do %><i class="glyphicon glyphicon-eye-open"></i><% end %>
                  <%= link_to edit_client_path(client), class: "btn btn-info" do %><i class="glyphicon glyphicon-edit"></i><% end %>
                  <%= link_to client, method: :delete, data: { confirm: 'Confirma exclusão ?' }, class: "btn btn-info" do %><i class="glyphicon glyphicon-trash"></i><% end %>
                </div>
              </td>
              <!-- <td><%= link_to 'Show', client %></td>
              <td><%= link_to 'Edit', edit_client_path(client) %></td>
              <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <h5 class="col-md-10">Novo Cliente</h5>
          </div>
        </div>
        <div class="panel-body">
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="container">
  <div class="row">

    <!-- <p id="notice"><%= notice %></p> -->

    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <h5 class="col-md-10">Cliente</h5>
            <div class="col-md-2">
              <%= link_to edit_client_path(@client), class: "btn btn-warning pull-right" do %>
              <b>Editar
              <i class="glyphicon glyphicon-edit"></i></b>
              <% end %>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="col-md-6">
            <label class="control-label" for="inputNome">Nome</label>
            <input class="form-control" disabled="" id="inputNome" type="text" value="<%= @client.name %>"></input>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <h5 class="col-md-12">Projetos</h5>
          </div>
        </div>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Título</th>
              <th class="col-md-2"></th>
            </tr>
          </thead>
          <tbody>
            <% Project.where(client_id: @client.id).each do |project| %>
            <tr>
              <td><%= project.id %></td>
              <td><%= project.title %></td>
              <td>
                <div class="btn-group pull-right">
                  <%= link_to project, class: "btn btn-info" do %>
                  <i class="glyphicon glyphicon-eye-open"></i><% end %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="clearfix"></div>
    <br>
  </div>
</div>